import { defineConfig } from "@dyrected/core";
import { postgresAdapter } from "@dyrected/db-postgres";
import { cloudinaryStorage } from "@dyrected/storage-cloudinary";
import { z } from "zod";
import { Customers } from "./src/dyrected/collections/Customers";
import { Assets } from "./src/dyrected/collections/Assets";
import { Conversations } from "./src/dyrected/collections/Conversations";
import { Orders } from "./src/dyrected/collections/Orders";
import { PrintJobs } from "./src/dyrected/collections/PrintJobs";
import { Services } from "./src/dyrected/collections/Services";
import { PricingRules } from "./src/dyrected/collections/PricingRules";
import { Materials } from "./src/dyrected/collections/Materials";
import { Incidents } from "./src/dyrected/collections/Incidents";
import { Messages } from "./src/dyrected/collections/Messages";
import { Owners } from "./src/dyrected/collections/Owners";
import { Media } from "./src/dyrected/collections/Media";
import { ShopSettings } from "./src/dyrected/globals/ShopSettings";
import { quotePrintJob, QuotingInput } from "./src/lib/pricingEngine";
import { Pricing_rules, Services as ServicesType } from "@/dyrected-types";

export default defineConfig({
  admin: {
    meta: { titleSuffix: " | PrintOS" },
    branding: {
      primaryColor: "#A4193D",
      accentColor: "#FFDFB9",
      logoText: "PrintOS",
      fontSans: '"Plus Jakarta Sans", sans-serif',
      fontSerif: '"Fraunces", serif',
    },
  },
  ai: {
    provider: "agentrouter",
    model: "deepseek-v4-flash",
    apiKey: process.env.AGENTROUTER_API_KEY || process.env.OPENAI_API_KEY,
    systemPrompt: `
You are the AI Operations & Print Consultant for PrintOS, serving practical Nigerian commercial print and branding shops (like the best printers in Shomolu, Mushin, and Victoria Island, Lagos).

YOUR CORE MISSION:
You are NOT an automated checkout bot. You are an expert, friendly human-like print operations assistant. Customers do not know technical print industry jargon. Speak in simple, clear, everyday Nigerian business language.

CONVERSATION & DIAGNOSTIC INTAKE RULES:
1. Speak simple, direct English:
   - NEVER use confusing phrases like "matching pair", "margin erosion", "COGS", or "incremental cost".
   - Ask only 1 or 2 straightforward questions per turn.
2. Category-Specific Intake Guides:
   • PICTURE & CANVAS FRAMING:
     - Ask the size in inches (e.g. 8x10", 12x16", 16x20", 24x36").
     - Ask: "Do you already have the printed photos in hand, or should we print the digital/soft copy for you on our studio photo paper?"
     - Ask frame style preference (Classic Wood, Modern Matte Black, Gold Accent, or Stretched Canvas).
     - Glass protection: Standard frames include ultra-clear glass protection.
   • SHIRTS & APPAREL:
     - Ask quantity needed and garment type (Round-neck 100% cotton, Polo, Hoodie).
     - Ask about design print position: Front only, or Front + Back?
   • BANNERS & SIGNAGE:
     - Ask size (Width x Height in feet e.g. 10x4ft) or Roll-up Stand (standard 3x7ft).
     - Ask indoor vs outdoor use (to include grommets/eyelets).
   • BUSINESS CARDS:
     - Ask quantity (100, 200, 500 cards) and finish (Matte lamination, Gloss, or Velvet soft-touch).

CUSTOMER CONTACT & AUTOMATIC DATABASE PERSISTENCE:
- When the customer's requirements are clear, calculate the price with 'calculatePrintQuote' and ask:
  "What is your name and WhatsApp phone number so I can save your quote and prepare your production order?"
- THE MOMENT the customer provides their Name and Phone number (e.g. "Busola 08026910113"):
  1. IMMEDIATELY call the 'saveCustomerOrder' tool with their details, items, pricing, and job notes.
  2. NEVER ask for their name or phone number again once provided.
  3. Confirm the order reference generated by 'saveCustomerOrder' (e.g. "Thanks, Busola! I've saved your details and created order reference ORD-2026-... in our workshop system.").
  4. NEVER tell the customer to send photos to their own phone number. Tell them to send soft copies to the Shop's official WhatsApp line: **+234 802 000 0000** or use the in-chat quote button.

FINANCIAL LANGUAGE RULES:
- Use simple terms:
  • "Customer will pay" (Total price)
  • "70% Deposit" (to buy materials & blanks so production starts immediately)
  • "30% Balance on delivery" (paid when job is ready)
- Always use the calculatePrintQuote tool for mathematically verified pricing.
    `,
    tools: {
      calculatePrintQuote: {
        description:
          "Calculates exact, mathematically guaranteed print prices, 70% material deposits, and 30% balances based on current shop rules and base blank costs.",
        parameters: z.object({
          serviceId: z.string().optional().describe("Service slug e.g. srv-dtf-tshirt"),
          item: z.string().describe("Item name e.g. 'Custom T-Shirt'"),
          quantity: z.number().describe("Quantity needed"),
          width: z.number().optional().describe("Width in feet or inches"),
          height: z.number().optional().describe("Height in feet or inches"),
          sizeArea: z.string().optional().describe("Print area e.g. A4, A3, Front"),
          spec: z.string().optional().describe("Finishing specifications"),
        }),
        execute: async (input: QuotingInput, { db }) => {
          const [servicesRes, rulesRes] = await Promise.all([
            db.find({ collection: "services", limit: 100 }),
            db.find({ collection: "pricing_rules", limit: 100 }),
          ]);

          const result = quotePrintJob(input, servicesRes.docs as ServicesType[], rulesRes.docs as Pricing_rules[]);

          return {
            ...result,
            formattedTotal: `₦${result.totalPrice.toLocaleString()}`,
            formattedDeposit: `₦${result.depositRequired.toLocaleString()}`,
            formattedBalance: `₦${result.balanceDue.toLocaleString()}`,
          };
        },
      },
      saveCustomerOrder: {
        description:
          "Saves or updates the customer's contact record and creates the formal Quote & Print Job in the shop database with full job notes.",
        parameters: z.object({
          customerName: z.string().describe("Customer's full name"),
          customerPhone: z.string().describe("Customer's WhatsApp or phone number"),
          item: z.string().describe("Item name e.g. '8x10 Photo Frame'"),
          quantity: z.number().describe("Quantity being produced"),
          spec: z.string().describe("Production specifications and finishing"),
          totalPrice: z.number().describe("Total price in Naira"),
          depositRequired: z.number().describe("70% deposit amount in Naira"),
          balanceDue: z.number().describe("30% balance amount in Naira"),
          notes: z.string().optional().describe("Important job notes, e.g. 'Customer will WhatsApp 2 soft-copy photos for lab printing'"),
        }),
        execute: async (input, { db }) => {
          const cleanPhone = input.customerPhone.replace(/\D/g, "");
          const customerId = cleanPhone ? `cust-${cleanPhone}` : `cust-${Date.now()}`;
          const randomSuffix = Math.floor(1000 + Math.random() * 9000);
          const orderNumber = `ORD-${new Date().getFullYear()}-${randomSuffix}`;
          const orderId = `ord-${orderNumber.toLowerCase()}`;
          const jobId = `job-${orderNumber.toLowerCase()}`;

          // 1. Upsert Customer Record
          try {
            await db.create({
              collection: "customers",
              data: {
                id: customerId,
                name: input.customerName,
                phone: input.customerPhone,
                totalSpent: 0,
                outstandingDebt: 0,
              },
            });
          } catch {
            await db.update({
              collection: "customers",
              id: customerId,
              data: {
                name: input.customerName,
                phone: input.customerPhone,
              },
            }).catch(() => null);
          }

          // 2. Create Customer Order
          await db.create({
            collection: "orders",
            data: {
              id: orderId,
              orderNumber,
              customer: customerId,
              customerName: input.customerName,
              customerContact: input.customerPhone,
              subtotal: input.totalPrice,
              depositRequired: input.depositRequired,
              depositPaid: 0,
              balanceDue: input.balanceDue,
              paymentStatus: "unpaid",
              status: "quoteSent",
            },
          }).catch(() => null);

          // 3. Create Print Job Record
          const estimatedCost = Math.round(input.totalPrice * 0.6);
          await db.create({
            collection: "print_jobs",
            data: {
              id: jobId,
              order: orderId,
              item: input.item,
              quantity: input.quantity,
              quotedPrice: input.totalPrice,
              materialCost: estimatedCost,
              marginPercent: 40,
              marginStatus: "healthy",
              status: "quoted",
            },
          }).catch(() => null);

          return {
            success: true,
            orderNumber,
            customerName: input.customerName,
            customerPhone: input.customerPhone,
            message: `Order ${orderNumber} and customer profile for ${input.customerName} successfully saved in workshop database.`,
          };
        },
      },
    },
    rateLimit: {
      userMax: 60,
      projectMax: 600,
    },
  },
  accessPolicies: {
    isAdminOrOwner: "user != null",
    isManagerOrOwner: "user != null",
    isStaff: "user != null",
    isAuthenticated: "user != null",
    isPublic: "true",
  },
  collections: [
    Assets,
    Orders,
    PrintJobs,
    Customers,
    Conversations,
    Services,
    PricingRules,
    Materials,
    Incidents,
    Messages,
    Owners,
    Media,
  ],
  globals: [ShopSettings],
  storage: cloudinaryStorage({
    cloudName: process.env.CLOUDINARY_CLOUD_NAME || "print-os",
    apiKey: process.env.CLOUDINARY_API_KEY || "print-os-key",
    apiSecret: process.env.CLOUDINARY_API_SECRET || "print-os-secret",
    folder: "print-os",
  }),
  email: {
    from: process.env.EMAIL_FROM || "MyPrintOS <hello@printos.ng>",
    send: async ({ to, subject, html }) => {
      const nodemailer = await import("nodemailer");
      const transporter = nodemailer.createTransport({
        service: "gmail",
        auth: {
          user: process.env.GMAIL_USER || "",
          pass: process.env.GMAIL_APP_PASSWORD || "",
        },
      });

      await transporter.sendMail({
        from: process.env.EMAIL_FROM || "MyPrintOS <hello@printos.ng>",
        to,
        subject,
        html,
      });
    },
  },
  db: postgresAdapter({
    url: process.env.DATABASE_URL || "",
  }),
});
