/**
 * This file was automatically generated by Dyrected CLI.
 * DO NOT MODIFY IT BY HAND.
 */

export interface Media {
  id: string;
  filename: string;
  filesize: number;
  mimeType: string;
  url: string;
  width?: number;
  height?: number;
  focalPoint?: { x: number; y: number };
  blurhash?: string;
  sizes?: Record<
    string,
    { filename?: string; url?: string; width?: number; height?: number }
  >;
  createdAt: string;
  updatedAt: string;
  alt: string;
  caption?: string;
}

// URL field types
export type UrlFieldValue =
  | {
      type: "custom";
      url: string;
      label?: string;
    }
  | {
      type: "internal";
      url: string;
      relationTo: string;
      value: string;
      label?: string;
    };

// Backward compatibility for simple string URLs
export type UrlField = UrlFieldValue | string;

export interface Assets {
  id: string;
  title: string;
  customer?: Customers | string;
  orders?: Array<Orders | string>;
  assetType: "artwork" | "logo" | "proof" | "receipt" | "rawAsset";
  printInstructions?: string;
  filename: string;
  filesize?: number;
  mimeType: string;
  url: string;
  width?: number;
  height?: number;
  blurhash?: string;
  sizes?: Record<
    string,
    { filename?: string; url?: string; width?: number; height?: number }
  >;
  createdAt: string;
  updatedAt: string;
}

export interface Orders {
  id: string;
  orderNumber: string;
  customer?: Customers | string;
  assets?: Array<Assets | string>;
  conversation?: Conversations | string;
  customerName: string;
  customerContact?: string;
  subtotal?: number;
  depositRequired?: number;
  depositPaid?: number;
  balanceDue?: number;
  balanceDueDate?: string;
  paymentStatus: "unpaid" | "depositPaid" | "fullyPaid" | "overdue";
  status:
    | "draftQuote"
    | "quoteSent"
    | "confirmed"
    | "inProduction"
    | "completed"
    | "cancelled";
  createdAt: string;
  updatedAt: string;
}

export interface Print_jobs {
  id: string;
  order?: Orders | string;
  conversation?: Conversations | string;
  service?: Services | string;
  item: string;
  quantity: number;
  width?: number;
  height?: number;
  material?: Materials | string;
  spec?: string;
  quotedPrice: number;
  materialCost?: number;
  marginPercent?: number;
  marginStatus: "healthy" | "atRisk" | "lossMaking";
  status: "quoted" | "inProduction" | "completed" | "cancelled";
  sourceChannel: "webChat" | "telegram" | "manual";
  createdAt: string;
  updatedAt: string;
}

export interface Customers {
  id: string;
  name: string;
  phone: string;
  email?: string;
  company?: string;
  telegramHandle?: string;
  totalSpent?: number;
  outstandingDebt?: number;
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

export interface Conversations {
  id: string;
  customer?: Customers | string;
  customerName?: string;
  customerContact?: string;
  channel: "webChat" | "telegram" | "manual";
  status: "inProgress" | "completed" | "abandoned";
  createdAt: string;
  updatedAt: string;
}

export interface Services {
  id: string;
  name: string;
  displayTitle?: string;
  category: "apparel" | "largeFormat" | "stationery" | "framing" | "souvenirs";
  pricingEngine: "matrix" | "area" | "perimeter" | "flatRate";
  defaultMaterial?: string;
  baseBlankCost?: number;
  unit: "piece" | "sqft" | "pack" | "inch" | "unit";
  unitsPerPack?: number;
  customUnitLabel?: string;
  bestFor?: string;
  imageUrl?: string;
  isActive?: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface Pricing_rules {
  id: string;
  service: Services | string;
  pricingEngine: "matrix" | "area" | "perimeter" | "flatRate";
  sizeArea?: string;
  minQuantity?: number;
  maxQuantity?: number;
  unitPrice?: number;
  ratePerUnitArea?: number;
  ratePerLinearUnit?: number;
  targetMarginPercent: number;
  createdAt: string;
  updatedAt: string;
}

export interface Materials {
  id: string;
  name: string;
  category: "largeFormat" | "apparel" | "stationery" | "framing" | "souvenirs";
  unitCost: number;
  unit: string;
  lastUpdated?: string;
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

export interface Incidents {
  id: string;
  printJob?: Print_jobs | string;
  order?: Orders | string;
  type: "underquote" | "materialPriceSpike" | "reprint" | "overdueBalance";
  financialImpact: number;
  urgencyScore?: number;
  reason: string;
  recommendedAction?: string;
  draftedMessage?: string;
  status: "open" | "resolved";
  resolutionNote?: string;
  createdAt: string;
  updatedAt: string;
}

export interface Messages {
  id: string;
  conversation: Conversations | string;
  role: "customer" | "assistant" | "owner";
  content: string;
  timestamp?: string;
  createdAt: string;
  updatedAt: string;
}

export interface Admin {
  id: string;
  name: string;
  roles: ("owner" | "manager" | "operator")[];
  email: string;
  createdAt: string;
  updatedAt: string;
}

export interface Shop_settingsGlobal {
  shopName: string;
  currencySymbol: string;
  defaultDepositPercent: number;
  targetMarginThreshold: number;
  lossMarginThreshold: number;
  telegramBotHandle?: string;
  ownerPhoneNumber?: string;
}

export interface DyrectedSchema {
  collections: {
    assets: Assets;
    orders: Orders;
    print_jobs: Print_jobs;
    customers: Customers;
    conversations: Conversations;
    services: Services;
    pricing_rules: Pricing_rules;
    materials: Materials;
    incidents: Incidents;
    messages: Messages;
    admin: Admin;
    media: Media;
  };
  globals: {
    shop_settings: Shop_settingsGlobal;
  };
}

declare module "@dyrected/sdk" {
  interface Register {
    schema: DyrectedSchema;
  }
}
